export const RANDOM_NAMES: string[] = [
  "Traveller's Therapist",
  "Lee Chapel Bat Colony CEO",
  "The Ghost of John Robinson",
  "Crying in Leyburn at 3am",
  "Red Square Squirrel Mafia",
  "Mock Con Conspiracy Theorist",
  "D-Hall Chicken Tender Hoarder",
  "Colonnade Gargoyle Whisperer",
  "Someone's Phi Delt Cooler",
  "General's Ghost on a Segway",
  "Windfall Lost My Deposit",
  "The Palms Bathroom Sommelier",
  "Brusher's Run Ankle Destroyer",
  "SAB Movie Nobody Watched",
  "Sorority Court Feral Cat",
  "Washington Hall Ceiling Leak",
  "VMI Cannon Alarm Clock",
  "The Beau Biden Parking Lot",
  "Lexington's Only Uber Driver",
  "EC Honor System Snitch Bot",
  "Fancy Dress Blackout Historian",
  "Kathekon Has No Budget Left",
  "Natty Light in a Nalgene",
  "Lost My Sperrys at Windfall",
  "A Mink on the Colonnade",
  "Woods Creek Trail Menace",
  "Haunted Third Floor Graham-Lees",
  "Co-op Deli Line Survivor",
  "Pole Houses Noise Complaint",
  "The Phi Psi Parking Cone",
  "Baker 509 Smoke Detector",
  "Liberty Hall Ruins Goth",
  "Traveller Fan Account (Official)",
  "Red Square Hammock Hog",
  "GHQ Chicken Finger Truther",
  "Leyburn Library Nap Champion",
  "The Windfall Aux Cord Dictator",
  "Sorority Court Speed Walker",
  "VMI Parade Deck Confusion",
  "Mock Con Floor Manager Energy",
  "D-Hall Sunday Brunch Gremlin",
  "The Colonnade Speed Trap",
  "Lee Chapel Organ Jumpscare",
  "Lexington Parking Ticket Collector",
  "E-Cafe Smoothie Apologist",
  "The Palms Sticky Floor Archivist",
  "Graham-Lees Fire Drill Veteran",
  "Red Square Rain Sprinkler Victim",
  "Brusher's Run Knee Surgery Fund",
  "SAB Comedian Nobody Laughed At",
  "The Third Traveller Impersonator",
  "Woods Creek Bridge Troll",
  "Baker Dorm Elevator Hostage",
  "Fancy Dress Theme Leak Account",
  "GHQ Late Night Quesadilla",
  "Leyburn Printer Out of Toner",
  "Pole Houses Landlord Ghosted Me",
  "Windfall DJ Who Only Plays Pitbull",
  "VMI Keydets Halftime Confusion",
  "D-Hall Salad Bar Conspiracy",
  "Mock Con Delegate Impersonator",
  "The Phi Tau Basement Archaeologist",
  "Lee Chapel Tour Guide Gone Rogue",
  "Red Square Frisbee Casualty",
  "Colonnade Pigeon Union Rep",
  "Lexington Crosswalk Daredevil",
  "Co-op Swipe Negotiator",
  "The Palms Pool Table Hustler",
  "Graham-Lees Communal Shower Screamer",
  "Leyburn Fourth Floor Exile",
  "Baker Fire Escape Philosopher",
  "Sorority Court Porch Swing Squatter",
  "Windfall Cover Charge Protester",
  "Woods Creek Skinny Dipper",
  "GHQ Mozzarella Stick Insider",
  "VMI Rat Line Escape Artist",
  "D-Hall Soft Serve Machine Truther",
  "Red Square Petition Collector",
  "Mock Con Elephant Handler",
  "The Phi Kap DJ Request Denier",
  "Lee Chapel Wedding Crasher",
  "Lexington ABC Store Historian",
  "Brusher's Run Mud Pit Survivor",
  "SAB Event with 4 Attendees",
  "Colonnade Selfie Stick Tourist",
  "Traveller's Bronze Nose Polisher",
  "The Palms Dart Board Legend",
  "Baker Dorm Laundry Thief",
  "Leyburn Study Room Hoarder",
  "Pole Houses Porch Collapse Witness",
  "Graham-Lees Basement Cryptid",
  "D-Hall Waffle Iron Monopolist",
  "Red Square Slack Liner",
  "Windfall Bathroom Line Philosopher",
  "VMI Parapet Pigeon",
  "Sorority Court Sprinkler Malfunction",
  "GHQ Wrap Station Anarchist",
  "Mock Con Campaign Button Hoarder",
  "The Phi Delt Goldfish Genealogist",
  "Lee Chapel Crypt Tour Dropout",
  "Lexington Lime Scooter Ghost Rider",
  "Woods Creek After Dark Regrets",
  "Co-op 11pm Grilled Cheese",
  "Baker Hall Wi-Fi Dead Zone",
  "Leyburn Beanbag Territory Dispute",
  "Fancy Dress Costume Emergency",
  "Red Square Motivational Preacher",
  "Colonnade Steps Wipeout Compilation",
  "D-Hall Ice Cream Machine Skeptic",
  "The Palms Karaoke War Criminal",
  "Graham-Lees Roommate Lottery Loser",
  "VMI Cannon Flinch Compilation",
  "Windfall Lost Shoe Recovery Unit",
  "Brusher's Run Shortcut Discoverer",
  "Sorority Court Fairy Lights Inspector",
  "Mock Con Budget Overrun Specialist",
  "GHQ Chicken Tender Forensics",
  "Lee Chapel Bat Whisperer Intern",
  "Lexington Weather Complaint Bot",
  "Baker Elevator Button Masher",
  "Leyburn All-Nighter Hall of Fame",
  "Red Square Duck Pond Lobbyist",
  "Pole Houses Ceiling Fan Wobble",
  "D-Hall Mystery Meat Investigator",
  "The Phi Psi Basement Anthropologist",
  "Colonnade Photo Bomber",
  "Traveller Statue 2am Confessional",
  "Windfall Wristband Counterfeiter",
  "VMI Barracks Window Screamer",
  "Co-op Closing Time Negotiator",
  "Woods Creek Trail Ankle Casualty",
  "SAB Poster Nobody Read",
  "Graham-Lees Hot Water Lottery",
  "Fancy Dress Pregame Casualty",
  "Red Square Protest for Nothing",
  "Lexington Jaywalking Champion",
  "Baker Dorm Whiteboard Vandal",
  "Leyburn Computer Lab Fossil",
  "D-Hall Plate Stacking Champion",
  "Mock Con Yard Sign Thief",
  "GHQ Napkin Dispenser Wrestler",
  "Lee Chapel Stained Glass Critic",
  "Sorority Court Noise Ordinance",
  "The Palms Pitcher Night Economist",
  "Brusher's Run Starting Line Regret",
  "Colonnade Construction Cone",
  "Windfall Snapchat Historian",
  "VMI Mess Hall Food Critic",
  "Pole Houses Extension Cord Fire Hazard",
  "Graham-Lees RA Avoidance Expert",
  "Red Square Acapella Ambush",
  "D-Hall Cereal at Every Meal",
  "Baker Dorm Ceiling Stain Namer",
  "Leyburn Quiet Floor Violator",
];

export function getRandomName(): string {
  return RANDOM_NAMES[Math.floor(Math.random() * RANDOM_NAMES.length)];
}
